from odoo import fields, models


class ResConfigSettings(models.TransientModel):
    _inherit = "res.config.settings"

    default_document_due_move_account_id = fields.Many2one(
        'account.account', default_model='account.payment.document',
        string='Default Account for account moves\
         generated by expiration of documents.')

    default_expiration_move_journal_id = fields.Many2one(
        'account.journal', default_model='account.payment.document',
        string='Default Journal for account moves\
         generated by expiration of documents.')
